// @ts-nocheck — untyped build tooling (matches scripts/build-theme.mjs). It is
// only pulled into the type program because themes.test.ts imports it; the test
// casts the result to its real shape, so the tool stays type-safe where it's used.
// Pure theme-compiler core — no disk I/O (callers inject `load`). Turns a
// registry of {id,label,light,dark} VSCode-theme pairs into per-family CSS +
// a manifest. Any token a curated theme omits fills from VS Code's own default
// theme, then a registry backstop. Spec:
// docs/superpowers/specs/2026-07-11-uikit-theme-system-design.md

// Every token's key-chain (first present key wins). Alpha is stripped except
// for `rule` (a translucent hairline) — see RAW below.
const CHAINS = {
  bg: ['editor.background'],
  ink: ['foreground', 'editor.foreground'],
  accent: ['button.background', 'textLink.foreground'],
  surface: ['input.background', 'editorWidget.background'],
  'surface-raised': ['dropdown.background', 'editorWidget.background'],
  'on-accent': ['button.foreground'],
  'ink-soft': ['descriptionForeground', 'editorLineNumber.foreground', 'tab.inactiveForeground', 'activityBar.inactiveForeground'],
  success: ['terminal.ansiGreen', 'editorGutter.addedBackground', 'gitDecoration.addedResourceForeground'],
  error: ['editorError.foreground', 'errorForeground'],
  warning: ['editorWarning.foreground', 'list.warningForeground'],
  // Info/notice + the app's drag/drop/active-hint highlight (the ex-`blue`).
  info: ['editorInfo.foreground', 'charts.blue', 'terminal.ansiBlue', 'textLink.foreground'],
  rule: ['input.border', 'dropdown.border', 'editorGroup.border'],
  // A card/widget border, a touch stronger than the hairline `rule`.
  'widget-border': ['editorWidget.border', 'panel.border', 'menu.border', 'contrastBorder']
};
const RAW = new Set(['rule', 'widget-border']); // keep alpha (translucent borders)
// Identity — MUST come from the curated theme itself (throw before any fallback).
const IDENTITY = new Set(['bg', 'ink', 'accent']);
// Keys VS Code sources from its color registry, not the default theme JSON.
// (editorWarning.foreground — platform/theme/common/colors/editorColors.ts)
const REGISTRY_BACKSTOP = {
  warning: { light: '#bf8803', dark: '#cca700' },
  // VS Code's info blue — used only if a theme AND the VS Code default both omit it.
  info: { light: '#1a85ff', dark: '#3794ff' }
};
// pepita tokens computed from other vars (not a VS Code color). Resolve at
// use-time, so they follow whichever scope's --ink/--bg/--surface-raised is active.
const DERIVED = {
  'ink-faint': 'color-mix(in srgb, var(--ink) 40%, var(--bg))',
  'code-bg': 'var(--surface-raised)',
  // Modal scrim — a dimming layer, identical in light/dark (it darkens whatever is
  // behind the dialog). A fixed value in the theme layer, not a palette colour.
  overlay: 'rgb(0 0 0 / 0.32)'
};

// Emission order per scope.
const TOKENS = ['bg', 'ink', 'ink-soft', 'ink-faint', 'accent', 'on-accent', 'surface', 'surface-raised', 'code-bg', 'rule', 'widget-border', 'success', 'error', 'warning', 'info', 'overlay'];

function norm(hex, key, ctx, keepAlpha) {
  if (typeof hex !== 'string' || !/^#[0-9a-fA-F]{3,8}$/.test(hex))
    throw new Error(`bad color for "${key}" in ${ctx}: ${JSON.stringify(hex)}`);
  let h = hex.slice(1);
  if (h.length === 3 || h.length === 4) h = [...h].map((c) => c + c).join('');
  return '#' + (keepAlpha ? h : h.slice(0, 6)).toLowerCase();
}
const pick = (colors, keys) => keys.find((k) => colors[k] !== undefined) || null;

// Three-tier resolve for one token: curated → VS Code default → registry backstop.
function resolveToken(tok, curated, fallback, brightness, ctx) {
  const keys = CHAINS[tok];
  const raw = RAW.has(tok);
  let k = pick(curated, keys);
  if (k) return { value: norm(curated[k], k, ctx, raw), from: 'theme' };
  if (IDENTITY.has(tok)) throw new Error(`required identity token "${tok}" missing from ${ctx} (tried ${keys.join(', ')})`);
  k = pick(fallback, keys);
  if (k) return { value: norm(fallback[k], k, `${ctx} (vscode-default)`, raw), from: 'vscode-default' };
  const b = REGISTRY_BACKSTOP[tok]?.[brightness];
  if (b) return { value: b, from: 'vscode-registry' };
  throw new Error(`no value for "${tok}" in ${ctx} (curated, default, and registry all empty)`);
}

function resolveScope(curated, fallback, brightness, ctx) {
  const values = {};
  const filled = [];
  for (const tok of Object.keys(CHAINS)) {
    const r = resolveToken(tok, curated, fallback, brightness, ctx);
    values[tok] = r.value;
    if (r.from !== 'theme') filled.push(`${tok}:${r.from}`);
  }
  for (const [tok, expr] of Object.entries(DERIVED)) values[tok] = expr;
  return { values, filled };
}

const pad = (s, n) => s + ' '.repeat(Math.max(0, n - s.length));
const block = (indent, v) => TOKENS.map((t) => `${indent}--${pad(t + ':', 15)} ${v[t]};`).join('\n');

function renderCss(id, label, L, D) {
  return `/* GENERATED by scripts/build-theme.mjs — ${label} (${id}). Do not edit by hand.
 * Runtime-swappable theme file. OS controls light/dark; [data-theme] forces it.
 * Regenerate with: pnpm gen:theme
 */
:root {
${block('  ', L)}
}
@media (prefers-color-scheme: dark) {
  :root {
${block('    ', D)}
  }
}
[data-theme='light'] {
${block('  ', L)}
}
[data-theme='dark'] {
${block('  ', D)}
}
`;
}

/**
 * @param {{ themes: { id: string, label: string, light: string, dark: string }[], defaults: { light: string, dark: string }, load: (f: string) => { colors?: Record<string, string> } }} args
 * @returns {{ files: Record<string, string>, manifest: { default: string, themes: { id: string, label: string }[] }, info: string[] }}
 */
export function buildThemes({ themes, defaults, load }) {
  const defLight = load(defaults.light).colors || {};
  const defDark = load(defaults.dark).colors || {};
  const files = {};
  const info = [];
  const manifestThemes = [];
  for (const { id, label, light, dark } of themes) {
    const L = resolveScope(load(light).colors || {}, defLight, 'light', `${id}/light`);
    const D = resolveScope(load(dark).colors || {}, defDark, 'dark', `${id}/dark`);
    if (L.filled.length) info.push(`${id} light filled: ${L.filled.join(', ')}`);
    if (D.filled.length) info.push(`${id} dark filled: ${D.filled.join(', ')}`);
    files[`${id}.css`] = renderCss(id, label, L.values, D.values);
    manifestThemes.push({ id, label });
  }
  const manifest = { default: themes[0].id, themes: manifestThemes };
  files['themes.json'] = JSON.stringify(manifest, null, 2) + '\n';
  files['theme.css'] = files[`${themes[0].id}.css`]; // back-compat alias = default family
  return { files, manifest, info };
}
